name: Status

on:
  workflow_dispatch:

  schedule:
    - cron: '*/5 * * * *'

jobs:
  status:
    runs-on: ubuntu-latest
    continue-on-error: ${{matrix.experimental}}
    strategy:
      matrix:
        port: [22, 22333, 23541, 24222, 24242, 24426, 24444, 24808, 25202, 26002, 26022]
        experimental: [false]
        include:
          - port: 27001
            experimental: true
      fail-fast: false

    steps:
      - name: Check the status of buildbots
        env:
          PORT: ${{matrix.port}}
        run: ssh-keyscan -p $PORT relay.aosc.io
