name: Status

on:
  workflow_dispatch:

  schedule:
    - cron: '*/5 * * * *'

jobs:
  status:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        port: [22, 22040, 22041, 22162, 22238, 22333, 23269, 23541, 24114, 24222, 24242, 24426, 24612, 24808, 25202, 25888, 26128, 26666, 26999, 27001, 27221, 27282, 27514, 27777, 27863, 27888, 28002, 28003, 28004]
        host: ["relay.aosc.io", "relay-inet.aosc.io", "relay-cn.aosc.io"]
      fail-fast: false

    steps:
      - name: Check the status of buildbots
        env:
          PORT: ${{matrix.port}}
          HOST: ${{matrix.host}}
        run: ssh-keyscan -p $PORT -T 240 $HOST
