name: Status

on:
  workflow_dispatch:

  schedule:
    - cron: '*/5 * * * *'

jobs:
  status:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        port: [22, 22333, 23541, 23869, 24191, 24426, 24451, 24808, 25202, 26055, 26056, 26666, 28002, 28003]
      fail-fast: false

    steps:
      - name: Check the status of buildbots
        env:
          PORT: ${{matrix.port}}
        run: ssh-keyscan -p $PORT relay.aosc.io
