name: Status

on:
  workflow_dispatch:

  schedule:
    - cron: '*/5 * * * *'

jobs:
  status:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        port: [22, 22333, 23269, 23541, 24114, 24222, 24242, 24426, 24808, 25202, 26666, 26999, 27282, 27514, 27863, 28002, 28003]
        host: ["relay.aosc.io", "relay-inet.aosc.io", "relay-cn.aosc.io"]
        experimental: [false]
        include:
          - port: 24514
            host: relay.aosc.io
            experimental: true
          - port: 24514
            host: relay-inet.aosc.io
            experimental: true
          - port: 24514
            host: relay-cn.aosc.io
            experimental: true
          - port: 26128
            host: relay.aosc.io
            experimental: true
          - port: 26128
            host: relay-inet.aosc.io
            experimental: true
          - port: 26128
            host: relay-cn.aosc.io
            experimental: true
      fail-fast: false

    steps:
      - name: Check the status of buildbots
        env:
          PORT: ${{matrix.port}}
          HOST: ${{matrix.host}}
        run: ssh-keyscan -p $PORT -T 240 $HOST
