name: Status

on:
  workflow_dispatch:

  schedule:
    - cron: '*/5 * * * *'

jobs:
  status:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        port: [22, 22333, 23541, 24114, 24426, 24514, 24808, 25202, 26666, 27863, 28002, 28003]
        host: ["relay.aosc.io", "relay-inet.aosc.io", "relay-cn.aosc.io"]
      fail-fast: false

    steps:
      - name: Check the status of buildbots
        env:
          PORT: ${{matrix.port}}
          HOST: ${{matrix.host}}
        run: ssh-keyscan -p $PORT -T 240 $HOST
