name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Find all buildbots which have new or different keys from those in the sorted file ssh_known_hosts.old
        run: |
          set +e
          
          ssh-keyscan -p 22162 -T 240 relay.aosc.io > ssh_known_hosts.new
          ssh-keyscan -p 22333 -T 240 relay.aosc.io > ssh_known_hosts.new
          ssh-keyscan -p 23269 -T 240 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 23541 -T 240 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 24114 -T 240 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 24222 -T 240 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 24242 -T 240 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 24426 -T 240 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 24808 -T 240 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 25202 -T 240 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 25888 -T 240 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 26128 -T 240 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 26666 -T 240 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 26999 -T 240 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 27001 -T 240 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 27282 -T 240 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 27514 -T 240 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 27688 -T 240 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 27863 -T 240 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 27888 -T 240 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 28002 -T 240 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 28003 -T 240 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 28004 -T 240 relay.aosc.io >> ssh_known_hosts.new
          
          ssh-keyscan -p 22162 -T 240 relay-inet.aosc.io > ssh_known_hosts.new
          ssh-keyscan -p 22333 -T 240 relay-inet.aosc.io > ssh_known_hosts.new
          ssh-keyscan -p 23269 -T 240 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 23541 -T 240 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 24114 -T 240 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 24222 -T 240 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 24242 -T 240 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 24426 -T 240 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 24808 -T 240 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 25202 -T 240 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 25888 -T 240 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 26128 -T 240 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 26666 -T 240 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 26999 -T 240 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 27001 -T 240 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 27282 -T 240 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 27514 -T 240 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 27688 -T 240 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 27863 -T 240 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 27888 -T 240 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 28002 -T 240 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 28003 -T 240 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 28004 -T 240 relay-inet.aosc.io >> ssh_known_hosts.new
          
          ssh-keyscan -p 22162 -T 240 relay-cn.aosc.io > ssh_known_hosts.new
          ssh-keyscan -p 22333 -T 240 relay-cn.aosc.io > ssh_known_hosts.new
          ssh-keyscan -p 23269 -T 240 relay-cn.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 23541 -T 240 relay-cn.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 24114 -T 240 relay-cn.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 24222 -T 240 relay-cn.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 24242 -T 240 relay-cn.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 24426 -T 240 relay-cn.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 24808 -T 240 relay-cn.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 25202 -T 240 relay-cn.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 25888 -T 240 relay-cn.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 26128 -T 240 relay-cn.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 26666 -T 240 relay-cn.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 26999 -T 240 relay-cn.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 27001 -T 240 relay-cn.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 27282 -T 240 relay-cn.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 27514 -T 240 relay-cn.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 27688 -T 240 relay-cn.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 27863 -T 240 relay-cn.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 27888 -T 240 relay-cn.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 28002 -T 240 relay-cn.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 28003 -T 240 relay-cn.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 28004 -T 240 relay-cn.aosc.io >> ssh_known_hosts.new

          ssh-keyscan -4 -p 23541 home.biscuit.moe >> ssh_known_hosts.new
          ssh-keyscan -4 -p 2223 kp920.ip4.run >> ssh_known_hosts.new
          ssh-keyscan -p 8022 nas.xinmu.moe >> ssh_known_hosts.new
          ssh-keyscan -p 2222 211.137.78.121 >> ssh_known_hosts.new

          ssh-keyscan repo.aosc.io >> ssh_known_hosts.new
          ssh-keyscan repo-cn.aosc.io >> ssh_known_hosts.new
          
          set -e
          
          sed -i 's/#.*$//;/^$/d' ssh_known_hosts
          sort -u ssh_known_hosts > ssh_known_hosts.old
          sort -u ssh_known_hosts.new ssh_known_hosts.old | diff -s ssh_known_hosts.old -
