name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Find all buildbots which have new or different keys from those in the sorted file ssh_known_hosts.old
        run: |
          set +e
          
          ssh-keyscan -p 22333 relay.aosc.io > ssh_known_hosts.new
          ssh-keyscan -p 23541 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 23869 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 24191 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 24426 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 24808 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 25202 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 26055 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 26056 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 26666 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 27863 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 28002 relay.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 28003 relay.aosc.io >> ssh_known_hosts.new
          
          ssh-keyscan -p 22333 relay-inet.aosc.io > ssh_known_hosts.new
          ssh-keyscan -p 23541 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 23869 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 24191 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 24426 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 24808 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 25202 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 26055 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 26056 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 26666 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 27863 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 28002 relay-inet.aosc.io >> ssh_known_hosts.new
          ssh-keyscan -p 28003 relay-inet.aosc.io >> ssh_known_hosts.new
          
          ssh-keyscan repo.aosc.io >> ssh_known_hosts.new
          
          set -e
          
          sed -i 's/#.*$//;/^$/d' ssh_known_hosts
          sort -u ssh_known_hosts > ssh_known_hosts.old
          sort -u ssh_known_hosts.new ssh_known_hosts.old | diff -s ssh_known_hosts.old -
